language: php
php:
  - 7.1
  - 7.2
  - 7.3
  - 7.4

before_script:
  - phpenv config-rm xdebug.ini
  - wget http://getcomposer.org/composer.phar
  - php -d memory_limit=4G composer.phar install

script:
  - bin/atoum
  - bin/php-cs-fixer fix --dry-run --stop-on-violation --diff --ansi
