language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - 7

before_script:
  - phpenv config-rm xdebug.ini
  - wget http://getcomposer.org/composer.phar
  - php composer.phar install --dev

script:
  - bin/atoum
  - bin/coke
