parameters:
    m6web_log_bridge.log_request_listener.name: "m6web_log_bridge.log_request_listener"
    m6web_log_bridge.matcher.name: "m6web_log_bridge.matcher"
    m6web_log_bridge.matcher_class.name: "LogBridgeMatcher"
    m6web_log_bridge.config_parser.class: M6Web\Bundle\LogBridgeBundle\Config\Parser
    m6web_log_bridge.builder.class: M6Web\Bundle\LogBridgeBundle\Matcher\Builder
    m6web_log_bridge.matcher_proxy.class: M6Web\Bundle\LogBridgeBundle\Matcher\MatcherProxy
    m6web_log_bridge.log_request_listener.class: M6Web\Bundle\LogBridgeBundle\EventDispatcher\LogRequestListener
    m6web_log_bridge.log_content_formatter.class: M6Web\Bundle\LogBridgeBundle\Formatter\DefaultFormatter
    m6web_log_bridge.ignore_headers:
        - php-auth-pw


services:
    m6web_log_bridge.config_parser:
        class: %m6web_log_bridge.config_parser.class%
        arguments:
            - @router

    m6web_log_bridge.builder:
        class: %m6web_log_bridge.builder.class%
        arguments:
            - %m6web_log_bridge.resources%
            - %kernel.environment%
        calls:
            - [ setDispatcher, [ @event_dispatcher ] ]
            - [ setConfigParser, [ @m6web_log_bridge.config_parser ] ]
            - [ setCacheDir, [ %kernel.cache_dir% ] ]
            - [ isDebug, [ %kernel.debug% ] ]
            - [ setMatcherClassName, [ %m6web_log_bridge.matcher_class.name% ] ]

    m6web_log_bridge.matcher:
        class: %m6web_log_bridge.matcher_proxy.class%
        arguments:
            - @m6web_log_bridge.builder

    m6web_log_bridge.log_content_formatter:
        class: %m6web_log_bridge.log_content_formatter.class%
        arguments:
            - %kernel.environment%
            - %m6web_log_bridge.ignore_headers%
            - %m6web_log_bridge.prefix_key%
        calls:
            - [ setTokenStorage, [ !@security.token_storage ] ]